SET AUTOBATCHSEQU=D:\__SWITCH\Flows\SI2\Acrobat\SaveToOptimized.sequ
SET AUTOBATCHFINAL=0
SET AUTOBATCHDEST=
SET AUTOBATCHALTPATH=%1
SET AUTOBATCHALTOUTPUTPATH=%2
SET AUTOBATCHNOPROGRESS=yes
SET AUTOBATCHFILEEXT=
SET AUTOBATCHNOSUBFOLDERS=yes
"C:\Program Files (x86)\Adobe\Acrobat DC\Acrobat\Acrobat.exe" /n /h